clippy ci

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -14,6 +14,11 @@ test() {
     if [[ "$RESULT" -ne 0 ]]; then 
         echo "git-hooks: Test failed, stop pushing"
     fi
+    cargo +stable clippy
+    RESULT=$?
+    if [[ "$RESULT" -ne 0 ]]; then 
+        echo "git-hooks: clippy failed, stop pushing"
+    fi
     return $RESULT
 }
 
